### ISSUE TITLE
Describe `write` error

### ISSUE THREAD

**Issue by saulshanabrook** [rainforestapp/heroku.json#2]
```
=== Describing canada-development to heroku.json
Getting addons for canada-development... done
Getting environment variables canada-development... done

 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `write' for File:Class (NoMethodError)
    Backtrace:   /Users/saul/.heroku/plugins/heroku.json/lib/heroku/command/json.rb:32:in `describe'
                 /Users/saul/.heroku/client/lib/heroku/command.rb:206:in `send'
                 /Users/saul/.heroku/client/lib/heroku/command.rb:206:in `run'
                 /Users/saul/.heroku/client/lib/heroku/cli.rb:28:in `start'
                 /usr/bin/heroku:25

    Command:     heroku describe
    Plugins:     heroku-config
                 heroku-pipeline
                 heroku.json

    Version:     heroku-toolbelt/2.35.0 (universal-darwin12.0) ruby/1.8.7
```

**Comment by ukd1** [comment]
Just having a look at this now!

**Comment by ukd1** [comment]
@saulshanabrook you should run `heroku plugins:update heroku.json` - this should fix!

**Comment by saulshanabrook** [comment]
Thanks yeah it works fine now  

## 

Saul Shanabrook
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ukd1** [comment]
@saulshanabrook glad! How are you finding it?

**Comment by saulshanabrook** [comment]
The addons freezing is helpful. However I use config files for environmental variables. Like this:

```
heroku plugins:install git://github.com/joelvh/heroku-config.git
heroku config:push -o --filename configs/env/common.env
heroku config:push -o --filename configs/env/heroku.env
heroku config:push -o --filename configs/env/secret.env
heroku config:push -o --filename configs/env/dev.env
```

So the variable freezing is not as helpful. It would be nice if I could supply paths to variable files, instead of variable names and use `heroku-config` to push them to the app.

**Comment by ukd1** [comment]
@saulshanabrook I'll have a think about it - it's currently designed to snapshot the app at a certain point in time, copying the addons and variables.
